version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8050:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    php:
      build:
            context: .
            dockerfile: PHP.Dockerfile
      volumes:
            - ./app:/app
    mysql:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: 'admin'
        MYSQL_USER: 'poseidons'
        MYSQL_PASSWORD: 'admin'
        MYSQL_DATABASE: 'docker-test'
      volumes:
        - mysqldata:/var/lib/mysql
      ports:
        - 3309:3306

volumes:
  mysqldata: {}
              
